spec_win     : 128
spec_step    : 64
fft_win      : 512
fft_step     : 64
highpass     : 25
k            : 64
output       : 'models/v2_lstm_v4/'
input        : 'gs://wdp-data/audio_files/2011/'
version      : "v1.0"
