runtime: python37

instance_class: F2

handlers:
- url: /wdp/.*
  script: auto

- url: /wdp-app/.*
  static_files: static/index.html
  upload: static/index.html

- url: /(.+)
  static_files: static/\1
  upload: static/.*

- url: /
  static_files: static/index.html
  upload: static/index.html

# [START gae_python_mysql_env]
#env_variables:
#    CLOUDSQL_CONNECTION_NAME: your-connection-name
#    CLOUDSQL_USER: root
#    CLOUDSQL_PASSWORD: your-cloudsql-user-password
# [END gae_python_mysql_env]
