spec_win     : 128
spec_step    : 64
fft_win      : 512
fft_step     : 64
highpass     : 25
latent       : 32 
batch        : 10
version      : "v5.0"
epochs       : 5
epochs_sup   : 10
viz_k        : 100
inputs       : 'data/signature_whistles/'
output       : 'models/auto_tuning/'

