spec_win     : 64
spec_step    : 16

fft_win      : 512
fft_step     : 64
highpass     : 10

latent       : 64

embedding_batch: 1000
batch          : 25
version        : "v10.0"

epochs_sup      : 50
epochs_encoder  : 5
epochs_finetune : 5

transfer     : true
freeze       : false

frame_dist_th: 1.5
viz_k        : 128

conv_w       : 8
conv_h       : 8
conv_filters : 256

n_writers    : 5
min2write    : 3
max2write    : 100
min_len      : 5
subsample    : 1.0

sil          : 'data/classification_noise'
type_class   : 'data/classification'
unsupervised : 'data/unsupervised'
output       : 'models/v10_lstm_v1/'
input        : 'gs://wdp-ds-data/dolphin_ogg'

