spec_win     : 128
spec_step    : 96
fft_win      : 512
fft_step     : 256
highpass     : 25
latent       : 64
batch        : 100
version      : "v6.0"
epochs       : 15
epochs_sup   : 15
viz_k        : 100
sil          : 'data/classification_noise'
type_class   : 'data/classification'
unsupervised : 'data/unsupervised'
reconstruct  : 'data/reconstruction'
output       : 'models/v6_lstm_v1/'
input        : 'gs://wdp-ds-data/dolphin_ogg'
transfer     : true
freeze       : false