spec_win     : 64
spec_step    : 32

fft_win      : 512
fft_step     : 256
highpass     : 25

latent       : 64

embedding_batch: 1000
batch          : 10
version        : "v8.0"

epochs          : 10
epochs_encoder  : 5
epochs_sup      : 5
epochs_finetune : 5

transfer     : true
freeze       : false

frame_dist_th: 0.08
viz_k        : 128

conv_w       : 8
conv_h       : 32
conv_filters : 1024

n_writers    : 5
min2write    : 3
max2write    : 100
min_len      : 5

sil          : 'data/classification_noise'
type_class   : 'data/classification'
unsupervised : 'data/unsupervised'
output       : 'models/v8_lstm_v1/'
input        : 'gs://wdp-ds-data/2011'

