spec_win     : 128
spec_step    : 64

fft_win      : 512
fft_step     : 128
highpass     : 25

latent       : 256

embedding_batch: 1000
batch          : 10
version        : "v6.0"
epochs         : 50
epochs_sup     : 15

transfer     : true
freeze       : false

frame_dist_th: 7.0
viz_k        : 128

conv_w       : 8
conv_h       : 32
conv_filters : 1024

n_writers    : 5
min2write    : 3
max2write    : 100
min_len      : 5

sil          : 'data/classification_noise'
type_class   : 'data/classification'
unsupervised : 'data/unsupervised'
output       : 'models/v6_lstm_v1/'
input        : 'gs://wdp-ds-data/2011'

