spec_win     : 64
spec_step    : 16
fft_win      : 512
fft_step     : 64
highpass     : 0
latent       : 64 
batch        : 25
version      : "v3.0"
epochs       : 50
epochs_sup   : 50
viz_k        : 100
sil          : 'data/classification_noise'
type_class   : 'data/classification'
unsupervised : 'data/unsupervised'
reconstruct  : 'data/reconstruction'
output       : 'models/v3_lstm_v1/'
transfer     : true
freeze       : false