spec_win     : 128
spec_step    : 64
fft_win      : 512
fft_step     : 64
highpass     : 25
latent       : 64 
batch        : 25
version      : "v5.0"
epochs       : 50
epochs_sup   : 50
viz_k        : 100
sil          : 'data/classification_noise'
type_class   : 'data/classification'
unsupervised : 'data/unsupervised'
reconstruct  : 'data/reconstruction'
output       : 'models/v5_lstm_v1/'
transfer     : true
freeze       : false