spec_win     : 16
spec_step    : 8

fft_win      : 512
fft_step     : 64
highpass     : 10

latent       : 32

batch          : 10
version        : "v11_juv_small"

epochs       : 50

conv_w       : 8
conv_h       : 8
conv_filters : 64

n_writers    : 3

unsupervised : 'data/juv'
output       : 'models/v11_juv_small/'


