spec_win     : 64
spec_step    : 32
fft_win      : 256
fft_step     : 128
highpass     : 12
latent       : 128
batch        : 25
version      : "v6.0"
epochs       : 50
epochs_sup   : 15
viz_k        : 128
sil          : 'data/classification_noise'
type_class   : 'data/classification'
unsupervised : 'data/unsupervised'
reconstruct  : 'data/reconstruction'
output       : 'models/v6_lstm_v1/'
input        : 'gs://wdp-ds-data/dolphin_ogg'
transfer     : true
freeze       : false