spec_win     : 64
spec_step    : 16

fft_win      : 512
fft_step     : 64
highpass     : 10

latent       : 128

batch          : 10
version        : "v11_juv"

epochs       : 25

viz_k        : 256

conv_w       : 8
conv_h       : 32
conv_filters : 256

n_writers    : 3

unsupervised : 'data/juv'
output       : 'models/v11_juv/'


