spec_win     : 64
spec_step    : 32

fft_win      : 512
fft_step     : 64
highpass     : 25

latent       : 128

embedding_batch: 1000
batch          : 25
version        : "v6.0"
epochs         : 50
epochs_sup     : 15

transfer     : true
freeze       : false

frame_dist_th: 15.0
viz_k        : 128

conv_w       : 8
conv_h       : 32
conv_filters : 256

n_writers    : 10
min2write    : 5
max2write    : 100
min_len      : 5

sil          : 'data/classification_noise'
type_class   : 'data/classification'
unsupervised : 'data/unsupervised'
output       : 'models/v6_lstm_v1/'
input        : 'gs://wdp-ds-data/2011'

