spec_win     : 128
spec_step    : 64
fft_win      : 512
fft_step     : 64
highpass     : 25
latent       : 256 
batch        : 50
version      : "v2.0"
epochs       : 8
viz_k        : 100
sil          : 'data/classification_noise_large'
unsupervised : 'data/unsupervised_large'
output       : 'models/v2_lstm_v5/'