spec_win     : 64
spec_step    : 16
fft_win      : 512
fft_step     : 64
highpass     : 25
output       : 'models/v3_lstm_v1/'
input        : 'gs://wdp-ds-data/dolphin_ogg'
version      : "v3.0"
encoding     : 'data/encodings.csv'

# TODO Audio Config
# TODO Beam Config
