spec_win     : 128
spec_step    : 64
fft_win      : 512
fft_step     : 64
highpass     : 25
output       : 'models/v2_lstm_v8/'
input        : 'gs://wdp-ds-data/dolphin_ogg'
version      : "v2.0"
encoding     : 'data/encodings.csv'
