spec_win     : 128
spec_step    : 64
fft_win      : 512
fft_step     : 64
highpass     : 25
k            : 100
output       : 'models/v2_lstm_v5/'
input        : '/media/dkohlsdorf/GODZILLA/2011_wav/'
version      : "v2.0"
encoding     : 'data/encodings.csv'
